on: [push]

name: Release

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.7"]
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Set version
      run: bash -c 'echo "let appVersion = \"`git describe --abbrev=0 --tags` (`date +%F`)\""' > ./Sources/table-cli/Version.swift
    - name: Build
      run: swift build -c release
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: release-binary-${{ matrix.os }}
        if-no-files-found: warn
        retention-days: 1
        path: .build/x86_64-unknown-linux-gnu/release/table-cli
    - name: Upload OSX artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: release-binary-${{ matrix.os }}
        if-no-files-found: warn
        retention-days: 1
        path: .build/x86_64-apple-macosx/release/table-cli
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
    - name: Display structure of downloaded files
      run: ls -R        

