on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

name: Release

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest ]
        swift: ["5.10"]
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}
    - name: Run tests
      run: swift test        
    - name: Set version
      run: bash -c 'echo "let appVersion = \"`git describe --abbrev=0 --tags` (`date +%F`)\""' > ./Sources/table/Version.swift  
    - name: Build Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: swift build -c release
    - name: Rename file
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: bash -c 'mv .build/release/table ./table'
    - name: Build OSX x86_64
      if: ${{ matrix.os == 'macos-latest' }}
      run: swift build -c release --arch x86_64
    - name: Rename x64 file
      if: ${{ matrix.os == 'macos-latest' }}
      run: bash -c 'mv .build/x86_64-apple-macosx/release/table ./table'      
    - name: Tar osx x86 file
      if: ${{ matrix.os == 'macos-latest' }}
      uses: a7ul/tar-action@v1.2.0
      with:
        command: c
        files: ./table
        outPath: osx_x86_64.tar.gz
    - name: Build OSX arm64
      if: ${{ matrix.os == 'macos-latest' }}
      run: swift build -c release --arch arm64
    - name: Rename arm64 file
      if: ${{ matrix.os == 'macos-latest' }}
      run: bash -c 'mv .build/arm64-apple-macosx/release/table ./table'      
    - name: Tar osx ARM file
      if: ${{ matrix.os == 'macos-latest' }}
      uses: a7ul/tar-action@v1.2.0
      with:
        command: c
        files: ./table
        outPath: osx_arm64.tar.gz
    - name: Tar linux file
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: a7ul/tar-action@v1.2.0
      with:
        command: c
        files: ./table
        outPath: linux.tar.gz
    - name: Upload linux artifact
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v4
      with:        
        name: release-binary-${{ matrix.os }}
        if-no-files-found: error
        retention-days: 1
        path: linux.tar.gz 
    - name: Upload OSX artifacts
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: release-binary-${{ matrix.os }}
        if-no-files-found: error
        retention-days: 1
        path: |
          osx_arm64.tar.gz
          osx_x86_64.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
    - name: List files
      run: ls -R
    - name: Create GH release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          ./release-binary-ubuntu-latest/linux.tar.gz
          ./release-binary-macos-latest/osx_arm64.tar.gz
          ./release-binary-macos-latest/osx_x86_64.tar.gz
